### ISSUE TITLE
Make initial UI Cleanups

### ISSUE THREAD

**Issue by mutterback** [ekitabu-LLC/ekitabu-readium-desktop-working#35]
[eKitabu Brand & Standards Guide - 2020.zip](https://github.com/ekitabu-LLC/ekitabu-readium-desktop-working/files/4871811/eKitabu.Brand.Standards.Guide.-.2020.zip)
[eKitabu Extended Color palette.pdf](https://github.com/ekitabu-LLC/ekitabu-readium-desktop-working/files/4871812/eKitabu.Extended.Color.palette.pdf)

1. Basic eKitabu branding - see logos, extended color palette
2. Navigation between books on device, cloud library (user specific OPDS) including books downloaded and books online, free books
3. Remove pop out reader option or button currently in Thorium
4. Default view on app open is all books, not recent
5. Move "About eKitabu e-reader" to a  Help icon on the top nav in the library view. Make help icon available during reader view.
6. While we are here, plan out larger UI changes to enable sort by Subject and Subject view as we implemented in Readium.js in Chrome

**Comment by brettins** [comment]
@mutterback is this still relevant or are we waiting for a UX pass on this?

**Comment by mutterback** [comment]
Closing as we agreed to do UX pass with Sean. Still not scheduled, but we need to do a comprehensive pass.
