### ISSUE TITLE
Change size of EPUB Footnote element in Readium Streamer

### ISSUE THREAD

**Issue by mutterback** [ekitabu-LLC/ekitabu-readium-desktop-working#39]
Hi Brett - this is a timely issue to look into. We're trying to use the HTML5 asisde, EPUB type:footnote element as a way to add videos of Kenyan Sign Language signs linked to vocabulary words. (See attached EPUB, page 

Here's a chat on Slack where Daniel Weck points to the code. We can set the video size to fit a reasonably sized footnote window.

Look at Erik Christopher and my dialog with Daniel Weck in the REadium Slack #general channel for the better formatting and links:
you could try to play with the CSS https://github.com/edrlab/r2-navigator-js-dist/blob/442bd1185a38973c1f729bd95357f6f717047aaf/dist/es6-es2015/src/electron/common/styles.js#L56-L60
dist/es6-es2015/src/electron/common/styles.js:56-60
    width: 90%;
    max-width: 40em;

    bottom: 1em;
    height: 7em;
Show more
<https://github.com/edrlab/r2-navigator-js-dist|edrlab/r2-navigator-js-dist>edrlab/r2-navigator-js-dist | Added by GitHub

danielweck:house_with_garden:  4 hours ago
(with a NPM post install patch in your package.json to modify the JS node_modules, or from the TS source https://github.com/readium/r2-navigator-js/blob/develop/src/electron/common/styles.ts
src/electron/common/styles.ts
```
// ==LICENSE-BEGIN==
// Copyright 2017 European Digital Reading Lab. All rights reserved.
// Licensed to the Readium Foundation under one or more contributor license agreements.
// Use of this source code is governed by a BSD-style license
Show more
<https://github.com/readium/r2-navigator-js|readium/r2-navigator-js>readium/r2-navigator-js | Added by GitHub

**Comment by brettins** [comment]
I'm not sure what element you're talking about. Can you provide a screenshot of where it is in the app?

**Comment by brettins** [comment]
I don't see an epub attached as mentioned.

**Comment by mutterback** [comment]
Hi - Daniel Wech is advising us to stick with pop ups. Let's move this to road map and consider it latter. I'm assigning back to me.

**Comment by mutterback** [comment]
CLosing per Daniel Weck's advice not to try to use footnotes for this purpose
