### ISSUE TITLE
Analytics Data Sync

### ISSUE THREAD

**Issue by kevinmainairungu** [ekitabu-LLC/ekitabu-readium-desktop-working#50]
Hi @brettins, We recently visited Kambui and Agha khan Primary, both of them have the DLP2 devices ad the Desktop app installed. 
<img width="1440" alt="Screen Shot 2020-11-24 at 6 22 52 PM" src="https://user-images.githubusercontent.com/23236275/100742344-af851e00-33eb-11eb-8c58-6628ab664535.png">
<img width="1440" alt="Screen Shot 2020-11-24 at 6 02 20 PM" src="https://user-images.githubusercontent.com/23236275/100742361-b6ac2c00-33eb-11eb-839c-435e91be02e4.png">

The app was not able to register some device information. I also noticed that some of the devices took more time to sync data. The longer it took the more usage data I got.

**Comment by mutterback** [comment]
Hi @kevinmainairungu is this a question or just an FYI to @brettins ?

This seems to be 2 issues. I suggest you split it into 1 or 2 new issues. I'm not quite sure if the 2nd one is a bug or just an observation:

1. Registration failure. Any more details on these devices or sense of why this happened? This seems to be either a bug or a gap in our process, whereby if a device doesn't synch on first open, it's never able to connect. This needs attention and work to ensure we're successfully able to synch devices that are not connected to the internet the 1st time the app is opened. I believe we've discussed elsewhere.

2. More time to sync = more data? Do you think this is a function of the fact that the devices had collected more data and therefore required more to sync? Or that somehow the more time a device is synching, it's somehow generating more data or is more successful in synching? I don't quite understand this 2nd issue.

Thanks!

**Comment by kevinmainairungu** [comment]
@mutterback This is both an FYI and a question for @brettins as I continue to do the school visits and check the database data. @brettins would you happen to know why this is happening. Is it because of the firewall prompt? The firewall prompt asks the user to allow the app to access the network.

**Comment by kevinmainairungu** [comment]
@brettins @mutterback 

I would put split them like this: 

1. Firewall prompt. - We need to confirm whether the firewall is preventing Registration and also data syncing

2. Time taken for the data to start syncing.  I'll need to confirm whether its the data size that's affecting data sync or it's just time required in general.

@dobbz could you kindly post the screenshots of the usage below? Thank you.

**Comment by dobbz** [comment]
Hi the images are too large. Over 10mb.
Let me upload to gdrive and share here

**Comment by brettins** [comment]
1 - Registration - The app should handle a failed initial sync, but let's create an issue with a proper bug report and I'll look into it. 
2 - This probably got lost in the shuffle of things, but currently the app is very naive and sends all of its analytics data every time it tries to sync with the remote DB. It isn't massively hard to change, but we decided to shelve that fix until later. If we want to to fix it it now, it just needs an issue created for it.

**Comment by mutterback** [comment]
Closing this issue and replacing with detailed bug reports
