### ISSUE TITLE
ereader-analytics-api on azure is down

### ISSUE THREAD

**Issue by dobbz** [ekitabu-LLC/ekitabu-readium-desktop-working#65]
@brettins There seems to be a problem with the API for production analytics sync. Could this be impacting why we can't seem to see any data from some devices. I was trying to understand why data wasn't syncing and came across this.

![Screenshot ereader-api Error](https://user-images.githubusercontent.com/16733688/102248911-d0cd2a80-3f12-11eb-95c2-a2271e493dee.png)
![Screenshot ereader-api success](https://user-images.githubusercontent.com/16733688/102248913-d1fe5780-3f12-11eb-84e7-c92f19d39081.png)

**Comment by brettins** [comment]
@mocyeg is prod up?

**Comment by mocyeg** [comment]
@brettins @dobbz 

the analytics API is working again. it looks like running the migrations automatically on deploy is causing failures. database migrations should be idempotent so I'm not sure why it's not working, but we can run them manually in the meantime

**Comment by brettins** [comment]
If we were left this long not knowing prod was down we should probably have some sort of uptime monitor going. Shouldn't matter now in the dev phase but later on we should have some phones ringing if shit goes down :P
